import type { Metadata } from "next";
import "./globals.css";
// import Header from "@/components/ui/Header";
import Footer from "@/components/ui/Footer";
import Heropage from "@/components/ui/Heropage";

export const metadata: Metadata = {
  title: "Hng 3a: Audiophile E-commerce Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <Heropage />
        {children}
        <Footer />
      </body>
    </html>
  );
}
